# Generated by Django 5.0.3 on 2024-06-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shopapp', '0008_alter_product_options_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.FileField(null=True, upload_to='orders/receipts/'),
        ),
    ]
